# 原文件中的配置
# target: diffbir.model.Diffusion
# params:
#   linear_start: 0.00085
#   linear_end: 0.0120
#   timesteps: 1000


# 训练文件中的
target: diffbir.model.gaussian_diffusion.Diffusion
params:
  linear_start: 0.00085
  linear_end: 0.0120
  timesteps: 1000
  zero_snr: False
  parameterization: eps